name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: kartoza/postgis:15-3
        env:
          POSTGRES_USER: user001
          POSTGRES_PASSWORD: 123456789
          POSTGRES_DB: gis
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Migrate database
      run: python manage.py makemigrations user_accounts

    - name: Migrate database
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test
