name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      pgdb:
        image: kartoza/postgis:15-3
        env:
          POSTGRES_USER: user001
          POSTGRES_PASSWORD: 123456789
          POSTGRES_DB: gis
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          binutils \
          libproj-dev \
          gdal-bin \
        && sudo rm -rf /var/lib/apt/lists/*
        pip install -r requirements.txt
      
    - name: Migrate database
      run: cd geousers && python manage.py makemigrations user_accounts

    - name: Migrate database
      run: cd geousers && python manage.py migrate

    - name: Run tests
      run: cd geousers && python manage.py test
